# Generated by Django 5.2.4 on 2025-08-02 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_userprofile_goal_alter_dailylog_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='calories',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='food',
            field=models.CharField(max_length=255),
        ),
    ]
