# Generated by Django 5.2.4 on 2025-08-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_dailylog_calories_alter_dailylog_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='calories_per_100g',
            field=models.FloatField(),
        ),
    ]
